### ISSUE TITLE
adding application to openauto_applications.ini

### ISSUE THREAD

**Issue by browntownington** [bgunson/onboardpi#43]
Hello :)

I couldnt see anywhere in your documentation how you configured the application in openauto_applications.ini

Would you be able to share the parameters? 

Many thanks!

**Comment by browntownington** [comment]
ooops found it! closing.

**Comment by bgunson** [comment]
[Here is the link in the wiki](https://github.com/bgunson/onboardpi/wiki/OpenAuto-Pro) for anyone else wondering
